### ISSUE TITLE
Lack of prerequisites

### ISSUE THREAD

**Issue by direwolf420** [MdTanjeemHaider/TPadder#1]
I'm getting an error when running this:
![Screenshot_2](https://github.com/MdTanjeemHaider/TPadder/assets/15894498/6a4b3c8b-d465-4952-bcc7-9ad3d639e992) is missing
and then
![Screenshot_3](https://github.com/MdTanjeemHaider/TPadder/assets/15894498/3fbaed79-11ff-48b3-94cb-d76ef1899e6d)

To clarify, I'm on WIndows 7, I heard newer python versions don't work on it, but haven't looked into it myself.

the github should list the prerequisites the user has to get in order to run this program

**Comment by MdTanjeemHaider** [comment]
Only the python code "TPadder.py" and the batch file "build.py" has prerequisites I believe. I'll add a prerequisite list for it soon.

To clarify, are you attempting to run the 'TPadder.py' code directly or are you trying to run the 'TPadder.exe' application? You can find the application on the [GitHub releases page](https://github.com/MdTanjeemHaider/TPadder/releases).

**Comment by MdTanjeemHaider** [comment]
miss clicked the "close as complete", reopening.

**Comment by direwolf420** [comment]
yeah I'm running the release exe

**Comment by MdTanjeemHaider** [comment]
The executable file was compiled using Python 3.11, and Windows 7 doesn't support that version. 
You can either:

1. Run the Python code directly: You can run the Python code (TPadder.py) instead of using the executable file. Make sure you have Python installed on your system. Download the latest compatible version of Python from the [official website](https://www.python.org/downloads/). Also, ensure that you have all the prerequisites listed on the README.

2. Build the executable yourself: If you prefer to have an executable file, you can build it yourself by running the build.bat file provided in the repository. Note that you will need all of the prerequisites listed on the README for this.
